#!/usr/bin/env python3

import sys
import pathlib


def main():
    if len(sys.argv) != 2:
        print("Script called with incorrect number of arguments")
        exit(2)  # Incorrect script usage

    [_, path] = sys.argv
    path = pathlib.Path(path).resolve()
    bench_result_path = path / "bench-result.json"

    with open(bench_result_path) as f:
        print(f.read())


if __name__ == "__main__":
    main()
